name: Criando uma descrição pro Workspace
description: Nessa página você descreve seu workspace, é só responder o que for perguntado, é fácil, pra começar, vamos dar um título pro seu workspace
title: "Lista de tarefas"
labels: ["none"]
body:
  - type: markdown
    attributes:
      value: |
        <big>Um bom nome para um workspace é completamente inteligível, por exemplo, se você está desenvolvendo uma lista de tarefas, não faz sentido usar "Super TaskLyst" ao invés disso coloque "Lista de tarefas" lembre-se que o Bee OS é orientado a intenção do usuário e não a aplicativos</big>
  - type: input
    id: _
    attributes:
      label: Agora sim nos diga o nome comercial
      description: O nome comercial é o nome que irá aparecer na loja
    validations:
      required: true
